services:
  django:
    image: sarthakghere/checkmate-django:latest
    env_file:
      - .env
    volumes:
      - ./mediafiles:/app/mediafiles
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db

  nginx:
    image: sarthakghere/checkmate-nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles:ro
      - ./mediafiles:/app/mediafiles:ro
    depends_on:
      - django

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  
  celery:
    image: sarthakghere/checkmate-django:latest
    container_name: celery
    command: celery -A CheckMate worker -l info
    env_file:
      - .env
    depends_on:
      - django
      - redis

  celery-beat:
    image: sarthakghere/checkmate-django:latest
    container_name: celery
    command: celery -A CheckMate beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - django
      - redis

volumes:
  db_data: